In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn
import warnings
warnings.filterwarnings("ignore")

In [2]:
data1 = pd.read_csv("UNSW_2018_IoT_Botnet_Full5pc_2.csv")

In [3]:
data1.head()

,pkSeqID,stime,flgs,flgs_number,proto,proto_number,saddr,sport,daddr,dport,...,AR_P_Proto_P_DstIP,N_IN_Conn_P_DstIP,N_IN_Conn_P_SrcIP,AR_P_Proto_P_Sport,AR_P_Proto_P_Dport,Pkts_P_State_P_Protocol_P_DestIP,Pkts_P_State_P_Protocol_P_SrcIP,attack,category,subcategory
0,1000001,1.528085e+09,e,1,udp,3,192.168.100.148,37153,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP
1,1000002,1.528085e+09,e,1,udp,3,192.168.100.148,37154,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP
2,1000003,1.528085e+09,e,1,udp,3,192.168.100.148,37155,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP
3,1000004,1.528085e+09,e,1,udp,3,192.168.100.148,37156,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP
4,1000005,1.528085e+09,e,1,udp,3,192.168.100.148,37157,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP

In [4]:
data2 = pd.read_csv("UNSW_2018_IoT_Botnet_Full5pc_4.csv")

In [5]:
data2.head()

,pkSeqID,stime,flgs,flgs_number,proto,proto_number,saddr,sport,daddr,dport,...,AR_P_Proto_P_DstIP,N_IN_Conn_P_DstIP,N_IN_Conn_P_SrcIP,AR_P_Proto_P_Sport,AR_P_Proto_P_Dport,Pkts_P_State_P_Protocol_P_DestIP,Pkts_P_State_P_Protocol_P_SrcIP,attack,category,subcategory
0,3000001,1.528099e+09,e,1,udp,3,192.168.100.147,6226,192.168.100.3,80,...,1.09825,100,100,1.09827,1.09825,1500,1500,1,DDoS,UDP
1,3000002,1.528099e+09,e,1,udp,3,192.168.100.147,6227,192.168.100.3,80,...,1.09825,100,100,1.09827,1.09825,1500,1500,1,DDoS,UDP
2,3000003,1.528099e+09,e,1,udp,3,192.168.100.147,6228,192.168.100.3,80,...,1.09825,100,100,1.09827,1.09825,1500,1500,1,DDoS,UDP
3,3000004,1.528099e+09,e,1,udp,3,192.168.100.147,6229,192.168.100.3,80,...,1.09825,100,100,1.09827,1.09825,1500,1500,1,DDoS,UDP
4,3000005,1.528099e+09,e,1,udp,3,192.168.100.147,6230,192.168.100.3,80,...,1.09825,100,100,1.09827,1.09825,1500,1500,1,DDoS,UDP

In [6]:
data1.shape

(1000000, 46)

In [7]:
data2.shape

(668522, 46)

In [8]:
data = data1.append(data2)

In [9]:
data.shape

(1668522, 46)

In [10]:
data.head()

,pkSeqID,stime,flgs,flgs_number,proto,proto_number,saddr,sport,daddr,dport,...,AR_P_Proto_P_DstIP,N_IN_Conn_P_DstIP,N_IN_Conn_P_SrcIP,AR_P_Proto_P_Sport,AR_P_Proto_P_Dport,Pkts_P_State_P_Protocol_P_DestIP,Pkts_P_State_P_Protocol_P_SrcIP,attack,category,subcategory
0,1000001,1.528085e+09,e,1,udp,3,192.168.100.148,37153,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP
1,1000002,1.528085e+09,e,1,udp,3,192.168.100.148,37154,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP
2,1000003,1.528085e+09,e,1,udp,3,192.168.100.148,37155,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP
3,1000004,1.528085e+09,e,1,udp,3,192.168.100.148,37156,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP
4,1000005,1.528085e+09,e,1,udp,3,192.168.100.148,37157,192.168.100.6,80,...,0.319943,100,100,0.319979,0.319943,800,800,1,DoS,UDP

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1668522 entries, 0 to 668521
Data columns (total 46 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   pkSeqID                           1668522 non-null  int64
 1   stime                             1668522 non-null  float64
 2   flgs                              1668522 non-null  object
 3   flgs_number                       1668522 non-null  int64
 4   proto                             1668522 non-null  object
 5   proto_number                      1668522 non-null  int64
 6   saddr                             1668522 non-null  object
 7   sport                             1668522 non-null  object
 8   daddr                             1668522 non-null  object
 9   dport                             1668522 non-null  object
 10  pkts                              1668522 non-null  int64
 11  bytes                             1668522 non-null  int64
 12  state                             1668522 non-null  object
 13  state_number                      1668522 non-null  int64
 14  ltime                             1668522 non-null  float64
 15  seq                               1668522 non-null  int64
 16  dur                               1668522 non-null  float64
 17  mean                              1668522 non-null  float64
 18  stddev                            1668522 non-null  float64
 19  sum                               1668522 non-null  float64
 20  min                               1668522 non-null  float64
 21  max                               1668522 non-null  float64
 22  spkts                             1668522 non-null  int64
 23  dpkts                             1668522 non-null  int64
 24  sbytes                            1668522 non-null  int64
 25  dbytes                            1668522 non-null  int64
 26  rate                              1668522 non-null  float64
 27  srate                             1668522 non-null  float64
 28  drate                             1668522 non-null  float64
 29  TnBPSrcIP                         1668522 non-null  int64
 30  TnBPDstIP                         1668522 non-null  int64
 31  TnP_PSrcIP                        1668522 non-null  int64
 32  TnP_PDstIP                        1668522 non-null  int64
 33  TnP_PerProto                      1668522 non-null  int64
 34  TnP_Per_Dport                     1668522 non-null  int64
 35  AR_P_Proto_P_SrcIP                1668522 non-null  float64
 36  AR_P_Proto_P_DstIP                1668522 non-null  float64
 37  N_IN_Conn_P_DstIP                 1668522 non-null  int64
 38  N_IN_Conn_P_SrcIP                 1668522 non-null  int64
 39  AR_P_Proto_P_Sport                1668522 non-null  float64
 40  AR_P_Proto_P_Dport                1668522 non-null  float64
 41  Pkts_P_State_P_Protocol_P_DestIP  1668522 non-null  int64
 42  Pkts_P_State_P_Protocol_P_SrcIP   1668522 non-null  int64
 43  attack                            1668522 non-null  int64
 44  category                          1668522 non-null  object
 45  subcategory                       1668522 non-null  object
dtypes: float64(15), int64(22), object(9)
memory usage: 598.3+ MB

In [12]:
data.isnull().sum()

pkSeqID                             0
stime                               0
flgs                                0
flgs_number                         0
proto                               0
proto_number                        0
saddr                               0
sport                               0
daddr                               0
dport                               0
pkts                                0
bytes                               0
state                               0
state_number                        0
ltime                               0
seq                                 0
dur                                 0
mean                                0
stddev                              0
sum                                 0
min                                 0
max                                 0
spkts                               0
dpkts                               0
sbytes                              0
dbytes                              0
rate                                0
srate                               0
drate                               0
TnBPSrcIP                           0
TnBPDstIP                           0
TnP_PSrcIP                          0
TnP_PDstIP                          0
TnP_PerProto                        0
TnP_Per_Dport                       0
AR_P_Proto_P_SrcIP                  0
AR_P_Proto_P_DstIP                  0
N_IN_Conn_P_DstIP                   0
N_IN_Conn_P_SrcIP                   0
AR_P_Proto_P_Sport                  0
AR_P_Proto_P_Dport                  0
Pkts_P_State_P_Protocol_P_DestIP    0
Pkts_P_State_P_Protocol_P_SrcIP     0
attack                              0
category                            0
subcategory                         0
dtype: int64

In [13]:
data.drop(["pkSeqID","flgs","proto","state","attack"],axis=1,inplace=True)

In [14]:
data.shape

(1668522, 41)

In [15]:
data.dtypes[data.dtypes=='object']

saddr          object
sport          object
daddr          object
dport          object
category       object
subcategory    object
dtype: object

In [16]:
data['saddr'].value_counts()

192.168.100.147              439157
192.168.100.150              412810
192.168.100.148              404693
192.168.100.149              400743
192.168.100.3                  5922
192.168.100.5                  5032
192.168.100.6                    42
192.168.100.7                    34
192.168.100.4                    19
192.168.100.1                    16
192.168.100.46                   15
192.168.100.27                   14
fe80::250:56ff:febe:254           6
fe80::c0c0:aa20:45b9:bdd9         4
192.168.100.55                    3
fe80::250:56ff:febe:e9d9          2
fe80::250:56ff:febe:c038          2
fe80::2c6a:ff9b:7e14:166a         2
fe80::250:56ff:febe:bf1a          2
fe80::250:56ff:febe:89ee          2
fe80::250:56ff:febe:26db          2
Name: saddr, dtype: int64

In [17]:
data['sport'].value_counts()

0x0303    8934
80        1259
2290      1032
1822      1032
1589      1032
          ...
6346         1
21710        1
9630         1
7565         1
10815        1
Name: sport, Length: 121216, dtype: int64

In [18]:
data['daddr'].value_counts()

192.168.100.3      1132026
192.168.100.5       199727
192.168.100.7       168814
192.168.100.6       156667
192.168.100.147       3136
                    ...
205.251.198.119          1
35.165.2.252             1
205.251.194.154          1
205.251.199.61           1
198.41.0.4               1
Name: daddr, Length: 84, dtype: int64

In [19]:
data['dport'].value_counts()

80        1424712
80         151629
1            6745
3306         4613
53            340
           ...
54744           1
2184            1
58014           1
0xb85d          1
48306           1
Name: dport, Length: 5207, dtype: int64

In [20]:
data['subcategory'].value_counts()

UDP                  1227144
TCP                   348751
Service_Scan           73168
OS_Fingerprint         17914
HTTP                     989
Normal                   477
Keylogging                73
Data_Exfiltration          6
Name: subcategory, dtype: int64

In [21]:
data['category'].value_counts()

DDoS              926624
DoS               650260
Reconnaissance     91082
Normal               477
Theft                 79
Name: category, dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["saddr_enc"] = le.fit_transform(data.saddr)
data["daddr_enc"] = le.fit_transform(data.daddr)
data["category_enc"]= le.fit_transform(data.category)
data["subcategory_enc"]= le.fit_transform(data.subcategory)
data.drop(['saddr','daddr','category','subcategory'],axis=1,inplace=True)

In [23]:
data['sport'] = data['sport'].astype(str)

In [24]:
search_string='0x'
result = set([i for i in data['sport'] if i.startswith(search_string)])
result

{'0x0008', '0x000d', '0x0011', '0x0303'}

In [25]:
data['sport'] = data['sport'].replace(['0x0303'],'771') 
data['sport'] = data['sport'].replace(['0x0011'],'17')
data['sport'] = data['sport'].replace(['0x000d'],'13')
data['sport'] = data['sport'].replace(['0x0008'],'8')

In [26]:
data["sport"] = data["sport"].astype(str).astype(int)

In [27]:
data['dport'] = data['dport'].astype(str)

In [28]:
data['dport'] = data.dport.apply(lambda x: int(x,16) if len(x)>1 and x[1]=="x" else int(x))

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1668522 entries, 0 to 668521
Data columns (total 41 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   stime                             1668522 non-null  float64
 1   flgs_number                       1668522 non-null  int64
 2   proto_number                      1668522 non-null  int64
 3   sport                             1668522 non-null  int32
 4   dport                             1668522 non-null  int64
 5   pkts                              1668522 non-null  int64
 6   bytes                             1668522 non-null  int64
 7   state_number                      1668522 non-null  int64
 8   ltime                             1668522 non-null  float64
 9   seq                               1668522 non-null  int64
 10  dur                               1668522 non-null  float64
 11  mean                              1668522 non-null  float64
 12  stddev                            1668522 non-null  float64
 13  sum                               1668522 non-null  float64
 14  min                               1668522 non-null  float64
 15  max                               1668522 non-null  float64
 16  spkts                             1668522 non-null  int64
 17  dpkts                             1668522 non-null  int64
 18  sbytes                            1668522 non-null  int64
 19  dbytes                            1668522 non-null  int64
 20  rate                              1668522 non-null  float64
 21  srate                             1668522 non-null  float64
 22  drate                             1668522 non-null  float64
 23  TnBPSrcIP                         1668522 non-null  int64
 24  TnBPDstIP                         1668522 non-null  int64
 25  TnP_PSrcIP                        1668522 non-null  int64
 26  TnP_PDstIP                        1668522 non-null  int64
 27  TnP_PerProto                      1668522 non-null  int64
 28  TnP_Per_Dport                     1668522 non-null  int64
 29  AR_P_Proto_P_SrcIP                1668522 non-null  float64
 30  AR_P_Proto_P_DstIP                1668522 non-null  float64
 31  N_IN_Conn_P_DstIP                 1668522 non-null  int64
 32  N_IN_Conn_P_SrcIP                 1668522 non-null  int64
 33  AR_P_Proto_P_Sport                1668522 non-null  float64
 34  AR_P_Proto_P_Dport                1668522 non-null  float64
 35  Pkts_P_State_P_Protocol_P_DestIP  1668522 non-null  int64
 36  Pkts_P_State_P_Protocol_P_SrcIP   1668522 non-null  int64
 37  saddr_enc                         1668522 non-null  int32
 38  daddr_enc                         1668522 non-null  int32
 39  category_enc                      1668522 non-null  int32
 40  subcategory_enc                   1668522 non-null  int32
dtypes: float64(15), int32(5), int64(21)
memory usage: 502.8 MB

In [30]:
data.head()

,stime,flgs_number,proto_number,sport,dport,pkts,bytes,state_number,ltime,seq,...,N_IN_Conn_P_DstIP,N_IN_Conn_P_SrcIP,AR_P_Proto_P_Sport,AR_P_Proto_P_Dport,Pkts_P_State_P_Protocol_P_DestIP,Pkts_P_State_P_Protocol_P_SrcIP,saddr_enc,daddr_enc,category_enc,subcategory_enc
0,1.528085e+09,1,3,37153,80,8,480,4,1.528085e+09,120567,...,100,100,0.319979,0.319943,800,800,2,20,1,7
1,1.528085e+09,1,3,37154,80,8,480,4,1.528085e+09,120568,...,100,100,0.319979,0.319943,800,800,2,20,1,7
2,1.528085e+09,1,3,37155,80,8,480,4,1.528085e+09,120569,...,100,100,0.319979,0.319943,800,800,2,20,1,7
3,1.528085e+09,1,3,37156,80,8,480,4,1.528085e+09,120570,...,100,100,0.319979,0.319943,800,800,2,20,1,7
4,1.528085e+09,1,3,37157,80,8,480,4,1.528085e+09,120571,...,100,100,0.319979,0.319943,800,800,2,20,1,7

In [31]:
data = data.sample(frac=1)
data

,stime,flgs_number,proto_number,sport,dport,pkts,bytes,state_number,ltime,seq,...,N_IN_Conn_P_DstIP,N_IN_Conn_P_SrcIP,AR_P_Proto_P_Sport,AR_P_Proto_P_Dport,Pkts_P_State_P_Protocol_P_DestIP,Pkts_P_State_P_Protocol_P_SrcIP,saddr_enc,daddr_enc,category_enc,subcategory_enc
901432,1.528096e+09,1,1,65381,80,1,154,3,1.528096e+09,250192,...,100,84,0.000000,29.771000,84,84,3,16,0,6
578244,1.526876e+09,1,1,46997,5566,2,120,1,1.526876e+09,966,...,100,100,18674.100000,76923.100000,200,200,4,16,3,4
21968,1.528085e+09,1,3,63953,80,13,780,4,1.528085e+09,142535,...,100,100,0.483786,0.483771,1300,1300,4,16,1,7
3930,1.528099e+09,1,3,8297,80,15,900,4,1.528099e+09,113153,...,100,100,1.098310,1.094650,1495,1495,1,16,0,7
293336,1.528099e+09,1,3,41114,80,15,900,4,1.528099e+09,140409,...,100,92,1.074070,1.052150,1468,1380,1,16,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55561,1.528085e+09,1,3,14921,80,13,780,4,1.528085e+09,176128,...,100,100,0.483823,0.483818,1300,1300,4,16,1,7
228870,1.528085e+09,1,3,29118,80,8,480,4,1.528085e+09,87282,...,100,100,0.246055,0.246063,800,800,1,21,1,7
409059,1.528099e+09,1,3,32760,80,6,360,4,1.528099e+09,256132,...,100,83,0.490694,0.544378,667,548,4,16,0,7
502389,1.528085e+09,1,3,40737,80,16,960,4,1.528085e+09,98647,...,100,100,0.665850,0.665470,1599,1599,4,16,1,7
3291,1.528099e+09,1,3,7981,80,15,900,4,1.528099e+09,112514,...,100,100,1.098320,1.073430,1466,1466,1,16,0,7

In [32]:
data['category_enc'].value_counts()

0    926624
1    650260
3     91082
2       477
4        79
Name: category_enc, dtype: int64

In [33]:
y = data['category_enc']

In [34]:
data.drop(["category_enc"],axis=1,inplace=True)

In [35]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features = data.iloc[:,:-1]
cols = features.columns
scaled_features = scaler.fit_transform(features)
data = pd.DataFrame(scaled_features,columns = cols)

In [36]:
data.head()

,stime,flgs_number,proto_number,sport,dport,pkts,bytes,state_number,ltime,seq,...,AR_P_Proto_P_SrcIP,AR_P_Proto_P_DstIP,N_IN_Conn_P_DstIP,N_IN_Conn_P_SrcIP,AR_P_Proto_P_Sport,AR_P_Proto_P_Dport,Pkts_P_State_P_Protocol_P_DestIP,Pkts_P_State_P_Protocol_P_SrcIP,saddr_enc,daddr_enc
0,0.246854,-0.284355,-1.726329,1.672483,-0.136198,-0.046128,-0.005902,-0.476284,0.246806,1.630986,...,-0.058234,-0.098396,0.376439,0.060879,-0.047209,-0.049578,-1.212634,-1.144914,0.409081,-0.558792
1,-2.986217,-0.284355,-1.726329,0.717206,1.018716,-0.040289,-0.006107,-2.388065,-2.986258,-1.591479,...,1.430719,2.979585,0.376439,0.703838,0.832223,3.256126,-1.002236,-0.923814,1.240302,-0.558792
2,0.218280,-0.284355,0.566935,1.598281,-0.136198,0.023949,-0.002142,0.479606,0.218303,0.238993,...,-0.058196,-0.103231,0.376439,0.703838,-0.047186,-0.050837,0.992920,1.172824,1.240302,-0.558792
3,0.256414,-0.284355,0.566935,-1.293738,-0.136198,0.035629,-0.001421,0.479606,0.256403,-0.140913,...,-0.058147,-0.103130,0.376439,0.703838,-0.047157,-0.050811,1.346607,1.544501,-1.253360,-0.558792
4,0.256454,-0.284355,0.566935,0.411512,-0.136198,0.035629,-0.001421,0.479606,0.256443,0.211504,...,-0.058149,-0.103137,0.376439,0.382359,-0.047158,-0.050812,1.297635,1.325307,-1.253360,-0.558792

In [37]:
import imblearn
from imblearn.over_sampling import RandomOverSampler
samp_strat = {0: 926624,1: 650260,2: 91082,3:91082,4:91082}
random_over = RandomOverSampler(sampling_strategy=samp_strat,random_state=1)
X_,y_ = random_over.fit_resample(data,y)
y_.value_counts()

0    926624
1    650260
4     91082
3     91082
2     91082
Name: category_enc, dtype: int64

In [38]:
import imblearn
from imblearn.under_sampling import RandomUnderSampler
samp_strat = {0: 91082,1: 91082,2: 91082,3: 91082,4:91082}
random_under = RandomUnderSampler(sampling_strategy=samp_strat,random_state=1)
X_1,y_1 = random_under.fit_resample(X_,y_)
y_1.value_counts()

4    91082
3    91082
2    91082
1    91082
0    91082
Name: category_enc, dtype: int64

In [39]:
from sklearn import model_selection
from sklearn.model_selection import StratifiedKFold,cross_val_score
from sklearn.svm import SVC

In [40]:
X_train,X_test,y_train,y_test = model_selection.train_test_split(X_1,y_1,test_size =0.25,random_state=42,stratify=y_1)

In [41]:
model = SVC(verbose=1,random_state=42)
model.fit(X_train,y_train)
model.score(X_test,y_test)

[LibSVM]

0.9993500390854875

In [42]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [43]:
print("Accuracy on training set:")
print(model.score(X_train,y_train))

Accuracy on training set:
0.9991509469868866

In [44]:
print("Accuracy on testing set:")
print(model.score(X_test,y_test))

Accuracy on testing set:
0.9993500390854875

In [45]:
y_pred = model.predict(X_test)
def get_classification_report(y_test, y_pred):
    from sklearn import metrics
    report = metrics.classification_report(y_test, y_pred, output_dict=True)
    df_classification_report = pd.DataFrame(report).transpose()
    df_classification_report = df_classification_report.sort_values(by=['f1-score'], ascending=False)
    return df_classification_report
get_classification_report(y_test,y_pred)

              precision   recall  f1-score       support
0              1.000000  1.00000  1.000000   22771.00000
1              1.000000  1.00000  1.000000   22770.00000
4              1.000000  1.00000  1.000000   22770.00000
macro avg      0.999352  0.99935  0.999350  113853.00000
accuracy       0.999350  0.99935  0.999350       0.99935
weighted avg   0.999352  0.99935  0.999350  113853.00000
2              0.996761  1.00000  0.998378   22771.00000
3              1.000000  0.99675  0.998372   22771.00000

In [46]:
confusion_matrix(y_test,y_pred)

array([[22771,     0,     0,     0,     0],
       [    0, 22770,     0,     0,     0],
       [    0,     0, 22771,     0,     0],
       [    0,     0,    74, 22697,     0],
       [    0,     0,     0,     0, 22770]], dtype=int64)

In [47]:
model = SVC()
skf = StratifiedKFold(n_splits=10,shuffle=True,random_state=42)
scores = cross_val_score(model,X_train,y_train,scoring='accuracy',cv=skf)
scores

array([0.9990924 , 0.99923879, 0.99900457, 0.99906312, 0.99906312,
       0.99900457, 0.99918023, 0.99912165, 0.99915093, 0.99877031])

In [48]:
from numpy import mean
mean(scores)

0.9990689689743901

In [49]:
params = {'gamma':[0.01,0.1],'C':(1,5)}
from sklearn.model_selection import GridSearchCV
model = SVC(random_state=42)
gscv = GridSearchCV(model,params,verbose=3,cv=3)
gscv.fit(X_train,y_train)
print("best score:",gscv.best_score_)
print("best params:",gscv.best_params_)

Fitting 3 folds for each of 4 candidates, totalling 12 fits

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] C=1, gamma=0.01 .................................................
[CV] ..................... C=1, gamma=0.01, score=1.000, total= 4.1min
[CV] C=1, gamma=0.01 .................................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  4.1min remaining:    0.0s

[CV] ..................... C=1, gamma=0.01, score=1.000, total= 4.8min
[CV] C=1, gamma=0.01 .................................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  8.9min remaining:    0.0s

[CV] ..................... C=1, gamma=0.01, score=1.000, total= 4.5min
[CV] C=1, gamma=0.1 ..................................................
[CV] ...................... C=1, gamma=0.1, score=1.000, total=40.2min
[CV] C=1, gamma=0.1 ..................................................
[CV] ...................... C=1, gamma=0.1, score=1.000, total=47.3min
[CV] C=1, gamma=0.1 ..................................................
[CV] ...................... C=1, gamma=0.1, score=1.000, total=47.9min
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=1.000, total= 5.9min
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=1.000, total= 6.2min
[CV] C=5, gamma=0.01 .................................................
[CV] ..................... C=5, gamma=0.01, score=1.000, total= 5.9min
[CV] C=5, gamma=0.1 ..................................................
[CV] ...................... C=5, gamma=0.1, score=1.000, total=29.9min
[CV] C=5, gamma=0.1 ..................................................
[CV] ...................... C=5, gamma=0.1, score=1.000, total=31.3min
[CV] C=5, gamma=0.1 ..................................................
[CV] ...................... C=5, gamma=0.1, score=1.000, total=45.1min

[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed: 273.0min finished

best score: 0.9999736501046184
best params: {'C': 5, 'gamma': 0.1}